language: php

dist: trusty

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "hhvm-3.12"
  - "hhvm-3.18"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
    - php: "nightly"
  include:
    - php: "7.1"
      env: DOCS=yes
    - php: "7.0"
      env: REQUIRE="phpmyadmin/motranslator:^3.0"
    - dist: precise
      php: "5.3"

sudo: false

install:
  - composer install
  - if [ -n "$REQUIRE" ] ; then composer require "$REQUIRE" ; fi
  - if [ "$DOCS" = "yes" ] ; then composer require "apigen/apigen dev-master#e381f7c" "roave/better-reflection dev-master#c87d856" ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache

script: 
  - if [ "$DOCS" != "yes" ] ; then ./vendor/bin/phpunit --configuration phpunit.xml ; fi
  - if [ "$DOCS" = "yes" ] ; then ./vendor/bin/apigen generate --destination doc src/ ; fi
