language: php

dist: trusty

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  - "hhvm-3.12"
  - "hhvm-3.18"
  - "nightly"

env:
  matrix:
    - MOTRANSLATOR=no

matrix:
  fast_finish: true
  allow_failures:
    - php: "nightly"
  include:
    - php: "7.0"
      env: MOTRANSLATOR=yes
    - dist: precise
      php: "5.3"

sudo: false

install:
  - composer install
  - if [ "$MOTRANSLATOR" = "yes" ] ; then composer require phpmyadmin/motranslator:^3.0 ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache

script: 
  - ./vendor/bin/phpunit --configuration phpunit.xml
