language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  - "hhvm"
  - "nightly"

env:
  matrix:
    - MOTRANSLATOR=yes
    - MOTRANSLATOR=no

matrix:
  fast_finish: true
  allow_failures:
    - php: "nightly"

sudo: false

install:
  - composer install
  - if [ "$MOTRANSLATOR" = "yes" ] ; then composer require phpmyadmin/motranslator:^3.0 ; fi

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      [[ -f ocular.phar ]] || wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache

script: 
  - ./vendor/bin/phpunit --configuration phpunit.xml
